[package]
name = "x5SimSearcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winconsole = "*"
reqwest = {version = "0.11.10", features = ["blocking"]}
serde_json = "*"